server:
  port: 8081

spring:
  profiles:
    active: @profiles.active@

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10

mybatis:
  type-aliases-package: com.blog.pojo
mapper:
  not-empty: false
  identity: mysql

---
spring:
  profiles: JeungNyeongJae
  application:
    name: web-service
  datasource:
    url: jdbc:mysql://188.131.229.61/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    username: root
    password: 1124
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  servlet:
    multipart:
      max-file-size: 5MB

---
spring:
  profiles: YunYeoHyang
  application:
    name: web-service
  datasource:
    url: jdbc:mysql://212.64.91.92/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    username: root
    password: 1124
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  servlet:
    multipart:
      max-file-size: 5MB

#  security:
#    user:
#      name: admin
#      password: admin
