server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://188.131.229.61/blog?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT
    username: root
    password: Admin999@
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  servlet:
    multipart:
      max-file-size: 5MB
  #  Redis
  redis:
    host: 188.131.229.61
    password: jeungnyeongjae
    port: 6379
    jedis:
      # pool settings
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  # ActiveMQ
  activemq:
    # ActiveMQ所在的服务器的地址
    broker-url: tcp://188.131.229.61:61616
    # 是否使用内置的MQ， true  使用； false  不使用
    in-memory: false
    # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    non-blocking-redelivery: false
    # 用户名 默认
    user: admin
    # 密码 默认
    password: admin

######################  MyBatis &  Mapper #############################
mybatis:
  type-aliases-package: com.blog.pojo
mapper:
  not-empty: false
  identity: mysql

